### ISSUE TITLE
Implement organizations [wip]

### ISSUE THREAD

**Issue by mprasil** [dani-garcia/bitwarden_rs#5]
There's some ground work laid out already, let's track the progress here. 
Endpoints to implement:
- [x] /api/organizations
- [x] /api/organizations/{orgId}/collections
- [x] /api/organizations/{orgId}/users
- [x] /organizations/{org_id}/collections/{coll_id}/users
- [x] /api/organizations/{orgId}/users/{orgUserId}/accept
- [x] /api/organizations/{orgId}/users/{orgUserId}/confirm
- [x] /api/organizations/{orgId}/users/invite
- [x] /api/organizations/users
- [x] /api/users/{userId}/public-key
- [x] /organizations/{org_id}/delete
- [x] /api/ciphers/{cipher_id}/collections-admin (#13)

Other changes:
- [x] /accounts/profile needs to list organizations for user
- [x] separate folder id from cipher to allow per-user folders (#10)
- [x] Respect the read_only bit when a user tries to modify a Cipher from a Collection
- [x] List all user Ciphers, including those from Collections the User has access to (#14)

**Comment by dani-garcia** [comment]
Yeah, the work on organizations is barely started. I don't have a lot of use for that functionality myself, and it's a pretty big change, so I don't have time at the moment to do it myself. That said, if you or anyone else would want to implement it, I'd gladly accept the PRs!

**Comment by dani-garcia** [comment]
With your PR and my latest fix (7e7c368) we can finally share ciphers between users with an organization.
For now, the Ciphers from the Organization are only available from the Organization page.

**Comment by mprasil** [comment]
Uhm.. so do we miss anything for this?  If we're ready to close it, can I suggest bumping the version to 0.2.0 or something? ✌️

**Comment by dani-garcia** [comment]
I forgot that we have a version 🤔 . We probably would be at 0.6.0 at least!

Yeeah, I think it's done, as far as I know. With this, the only thing left to be feature-equivalent with upstream would be: 
- implementing other 2Factor methods,  like YubiKey or U2F (I don't know how these work and I don't have the hardware to test, so I won't be personally implementing this)
- Enterprise features, like directory sync (I don't have a way to test this either, and I don't see much use for it, so I won't implement it)

I'll bump the version to 0.9.0, as in my view it's basically feature complete, but there might be bugs still. Once some time has passed and if there aren't any bugs left to fix, we could promote it to 1.0.
